#!/bin/bash

# Run this script to install python 2.7.11
# To run use sudo ./install_python
# Has to be executed ones per machine before running configure and run_zbuilder_smoke_tests
# Makes a new instance of python that matches Maya's python version to make installed libraries compatible
# configure and run_zbuilder_smoke_tests scripts will not work before this script executed
# Reference: https://danieleriksson.net/2017/02/08/how-to-install-latest-python-on-centos/

if test -f /usr/local/bin/python2.7; then
  if /usr/local/bin/python2.7 -V == "Python 2.7.11"; then
  echo "Python is satisfying requirements.";
  exit 0;
  else echo "Installing Python 2.7.11..."; fi
else echo "Installing Python 2.7.11..."; fi

yum install -y zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel expat-devel

yum install -y wget

wget http://python.org/ftp/python/2.7.11/Python-2.7.11.tar.xz
tar xf Python-2.7.11.tar.xz
cd Python-2.7.11 || { echo "Could not find python installation folder: Python-2.7.11"; exit 1; }
./configure --prefix=/usr/local/ --enable-unicode=ucs4 --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib/"
make && make altinstall

wget https://bootstrap.pypa.io/get-pip.py
/usr/local/bin/python2.7 get-pip.py

cd ..
rm -R Python-2.7.11
rm Python-2.7.11.tar.xz
