#!/bin/bash

# Execute to run zBuilder tests
# Has to be run after intall_python unless it was executed on current machine
# and after configute scripts from the current folder
# Optional input parameter: takes first argument as maya version number, default agrument is 2019

echo "activating virtual environment ..."

source ./env2/bin/activate

echo "done"

echo "adding home folder to zivadyn_LICENSE ..."

export zivadyn_LICENSE=$zivadyn_LICENSE:~

echo "done"

mayaYear=${1:-2019}

python ../../CMT/bin/runmayatests.py -m "$mayaYear" --path ./tests --maya-script-path ../../scripts

echo "deactivating virtual environment ..."

deactivate

echo "done"
