#!/bin/bash

# Execute to run zBuilder tests
# Read ./install_python and ./configure description before running
# To run use ./run_zbuilder_smoke_tests
# DO NOT run with sudo
# Optional input parameter: takes first argument as maya version number, default agrument is 2019

echo "activating virtual environment ..."

source ./env2/bin/activate

echo "done"

echo "adding home folder to zivadyn_LICENSE ..."

export zivadyn_LICENSE=$zivadyn_LICENSE:~

echo "done"

mayaYear=${1:-2019}

python ../../CMT/bin/runmayatests.py -m "$mayaYear" --path ./tests --maya-script-path ../../scripts

echo "deactivating virtual environment ..."

deactivate

echo "done"
